[17.0][MIG] partner_address_two_lines
trisdoan/partner-contact pull request #1
Opened 2024-03-09 11:40 UTC by trisdoan

### Changes in version 17.0

1.

2024-03-11 10:14 UTC, nguyenminhchien requested changes

2024-03-11 10:14 UTC, nguyenminhchien commented on partner_address_two_lines/models/res_partner.py
> +    def _get_complete_name(self):
Traceback (most recent call last):
  File "/home/chien/code/oca/partner-contact/17.0/partner_address_two_lines/tests/test_res_partner.py", line 35, in test_get_name
    self.child_partner_name.display_name, "Test Company Name\nTest Partner Name"
  File "/home/chien/code/odoo/odoo/17.0/odoo/fields.py", line 1206, in __get__
    self.compute_value(recs)
  File "/home/chien/code/odoo/odoo/17.0/odoo/fields.py", line 1388, in compute_value
    records._compute_field_value(self)
  File "/home/chien/code/odoo/odoo/17.0/odoo/models.py", line 4858, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/chien/code/odoo/odoo/17.0/odoo/fields.py", line 101, in determine
    return needle(*args)
  File "/home/chien/code/oca/partner-contact/17.0/partner_address_two_lines/models/res_partner.py", line 39, in _compute_display_name
    name = rec._get_complete_name()
  File "/home/chien/code/oca/partner-contact/17.0/partner_address_two_lines/models/res_partner.py", line 11, in _get_complete_name
    res = super()._get_complete_name()
AttributeError: 'super' object has no attribute '_get_complete_name'

2024-03-11 10:14 UTC, nguyenminhchien commented on partner_address_two_lines/models/res_partner.py
> +# Copyright 2024 Camptocamp SA
Don't change it
![image](https://github.com/trisdoan/partner-contact/assets/8724793/42b8ddb9-4cf2-4222-b93c-517f7173da14)

2024-03-12 03:05 UTC, nguyenminhchien requested changes

2024-03-12 03:05 UTC, nguyenminhchien commented on partner_address_two_lines/models/res_partner.py
> +            return "\n".join([n for n in splitted_names if n.strip()])
it's quite risky when using `res.split(", ")`. Imaging that i have:

- commercial_company_name = `TROBZ CO., LTD`
- name = `Trí`
- res will be `TROBZ CO., LTD, Trí`. So, the result will be `TROBZ CO.\nLTD\nTrí` which's different from expected `TROBZ CO., LTD\n Trí`

2024-03-12 03:05 UTC, nguyenminhchien commented on partner_address_two_lines/models/res_partner.py
> +                rec.display_name = name.strip()
Suggestion:

 ```
        if self.env.context.get("_two_lines_partner_address"):
            for rec in self:
                name = rec._get_complete_name()
                rec.display_name = name.strip()
        else:
            super()._compute_display_name()
```

2024-03-12 08:36 UTC, nguyenminhchien requested changes

2024-03-12 08:36 UTC, nguyenminhchien commented on partner_address_two_lines/models/res_partner.py
> +        return name.strip()
You should call super() in this function. Otherwise, it could lead to the conflict with other modules.

2024-03-12 08:36 UTC, nguyenminhchien commented on partner_address_two_lines/tests/test_res_partner.py
> +            {"name": "TROBZ CO., LTD", "company_type": "company"}
I'm ok with this, but in the past, people from OCA requested to replace a real company name by a non-existed one.

2024-03-12 10:33 UTC, nguyenminhchien requested changes

2024-03-12 10:33 UTC, nguyenminhchien commented on partner_address_two_lines/models/res_partner.py
>          if self.env.context.get("_two_lines_partner_address"):
Print the Quotation report (of sale.order), you can the `Gemini Furniture` and `YourCompany` were shown twice.
I checked v16 and saw that you should update this line to be:` if (self.company_name or self.parent_id) and not self.is_company and self.env.context.get("_two_lines_partner_address"):`
![image](https://github.com/trisdoan/partner-contact/assets/8724793/4784124e-ebe5-48de-9f5c-c466b14658bd)

2024-03-12 10:59 UTC, nguyenminhchien approved these changes

2024-04-29 04:29 UTC, trisdoan commented
### This change
- rename module
- change logic of `_compute_display_name`: instead of recalculating display_name, find ', ' and replace it with line break. The previous approach did not take into account odoo native's contexts such as show_address

2024-05-08 02:45 UTC, nguyenminhchien requested changes

2024-05-08 02:45 UTC, nguyenminhchien commented on partner_display_name_line_break/models/res_partner.py
> +            super()._compute_display_name()
super() has been called once at line 30

2024-05-08 02:45 UTC, nguyenminhchien commented on setup/partner_display_name_line_break/setup.py
> +import setuptools
run pre-commit to remove the setup folder. or, remove it manually

2024-05-08 02:48 UTC, trisdoan commented on partner_display_name_line_break/models/res_partner.py
> +            super()._compute_display_name()
yeah silly me :rofl:. Thanks a

2024-05-08 07:32 UTC, trisdoan commented
Hi anh @nguyenminhchien, this PR is superseded by https://github.com/trisdoan/partner-contact/pull/2

2024-05-08 07:32 UTC, closed without merging